import { BackroomsLevel, LevelInfo } from '../types';

export const LEVEL_DEFINITIONS: Record<BackroomsLevel, LevelInfo> = {
  level0: {
    id: 'level0',
    name: 'Nivel 0',
    codeName: 'El Monótono Amarillo (The Lobby)',
    dangerClass: 'Clase 0',
    description: 'Un espacio no lineal infinito compuesto por carpetas amarillas húmedas, papel tapiz idéntico y luces fluorescentes que zumban sin cesar.',
    wallType: 'wallpaper',
    floorType: 'carpet',
    fogColor: 0x998948,
    fogDensity: 0.045,
    lightColor: 0xffea9f,
    lightIntensity: 0.85,
    ambientHumType: 'fluorescent',
    hasEntities: true,
    spawnableEntities: ['bacteria', 'smiler'],
  },
  level1: {
    id: 'level1',
    name: 'Nivel 1',
    codeName: 'Zona Habitable',
    dangerClass: 'Clase 1',
    description: 'Un enorme almacén de hormigón gris con tuberías de vapor oxidadas y luces parpadeantes que sufren apagones repentinos.',
    wallType: 'concrete',
    floorType: 'concrete',
    fogColor: 0x22262a,
    fogDensity: 0.065,
    lightColor: 0x90a4ae,
    lightIntensity: 0.45,
    ambientHumType: 'pipes',
    hasEntities: true,
    spawnableEntities: ['bacteria', 'skinstealer'],
  },
  level37: {
    id: 'level37',
    name: 'Nivel 37',
    codeName: 'Poolrooms (Subliminal)',
    dangerClass: 'Clase 0',
    description: 'Estructuras infinitas de azulejos blancos sumergidas en agua tibia y cristalina. Una calma inquietante donde los ecos nunca terminan.',
    wallType: 'tiles',
    floorType: 'water',
    fogColor: 0x76c4ce,
    fogDensity: 0.025,
    lightColor: 0xdff9fb,
    lightIntensity: 1.1,
    ambientHumType: 'water_echo',
    hasEntities: true,
    spawnableEntities: ['smiler'],
  },
  level_run: {
    id: 'level_run',
    name: 'Nivel !',
    codeName: '¡Corre Por Tu Vida!',
    dangerClass: 'Clase 5',
    description: 'Un pasillo de hospital de 10 kilómetros iluminado con luces rojas de emergencia. Entidades implacables te persiguen desde atrás.',
    wallType: 'red_hospital',
    floorType: 'checker',
    fogColor: 0x5a0000,
    fogDensity: 0.05,
    lightColor: 0xff0000,
    lightIntensity: 1.2,
    ambientHumType: 'siren',
    hasEntities: true,
    spawnableEntities: ['bacteria', 'partygoer'],
  },
  level6: {
    id: 'level6',
    name: 'Nivel 6',
    codeName: 'Lights Out',
    dangerClass: 'Clase 4',
    description: 'Oscuridad absoluta e impenetrable. La privación sensorial es tan severa que el menor sonido revelará tu ubicación a las criaturas.',
    wallType: 'darkness',
    floorType: 'dark',
    fogColor: 0x010102,
    fogDensity: 0.18,
    lightColor: 0x111122,
    lightIntensity: 0.08,
    ambientHumType: 'whisper',
    hasEntities: true,
    spawnableEntities: ['smiler', 'skinstealer'],
  },
  level94: {
    id: 'level94',
    name: 'Nivel 94',
    codeName: 'Motion Town',
    dangerClass: 'Clase 3',
    description: 'Un vecindario de casas al estilo de dibujos animados con un cielo falso pintado y colinas de césped bajo un sol estático inquietante.',
    wallType: 'pastel',
    floorType: 'grass',
    fogColor: 0xb5d2eb,
    fogDensity: 0.035,
    lightColor: 0xfff4e0,
    lightIntensity: 0.95,
    ambientHumType: 'tv_static',
    hasEntities: true,
    spawnableEntities: ['partygoer'],
  },
};
